%ifndef IO_LIB_HEADERS
%define IO_LIB_HEADERS

global exit
global string_length
global print_string
global print_char
global print_newline
global print_uint
global print_int
global string_equals
global read_char
global read_word
global parse_uint
global parse_int
global string_copy
global read_str

extern exit
extern print_newline
extern print_string
extern find_word
extern read_str
extern read_word

%endif

